"""The Room interface — the seam between the shared platform and each game.

Every game variant ships a ``Room`` class. The shared socket layer (connection,
lobby, director, social) and the RoomManager only rely on the contract described
here, never on a specific game. Adding a variant = implement this interface in
``game/<variant>/room.py`` and register the class in ``core.registry``.

This is a typing.Protocol: it documents and (statically) checks the contract
without forcing inheritance. It is intentionally split into two tiers:

* **Lifecycle / identity / roster** — truly game-agnostic; identical for every
  variant. The manager, connection, and lobby room-management paths use only
  these.
* **Gameplay / view** — each variant provides these, but their payload *shapes*
  are still Super-Seven-flavoured in Phase 1. Phase 2 genericises how the lobby
  and client consume them. They are listed here so the seam is documented in one
  place; they are not yet a stable cross-game contract.
"""
from typing import Any, Dict, List, Optional, Protocol, runtime_checkable

from game.core.player import Player


@runtime_checkable
class RoomProtocol(Protocol):
    # ---- identity ----
    code: str
    host_id: str
    game_type: str
    state: str
    settings: dict
    table_theme: str
    created_at: float
    players: Dict[str, Player]

    # ---- lifecycle / roster (game-agnostic) ----
    def register_player(self, user_id: str, name: str) -> Player: ...
    def attach(self, user_id: str, sid: str) -> None: ...
    def detach(self, user_id: str) -> None: ...
    def remove_player(self, user_id: str) -> None: ...
    def remove_participant(self, user_id: str) -> None: ...
    def migrate_host(self) -> Optional[str]: ...
    def is_host(self, user_id: str) -> bool: ...
    def is_full(self) -> bool: ...
    def in_round(self) -> bool: ...
    def any_connected(self) -> bool: ...
    def any_human_connected(self) -> bool: ...
    def connected_players(self) -> List[Player]: ...
    def public_players(self) -> List[dict]: ...
    def reset_for_rematch(self) -> None: ...

    # ---- gameplay / view (variant-provided; shapes not yet cross-game stable) ----
    def start_round(self) -> None: ...
    def hand_for(self, user_id: str) -> Any: ...
    def public_round_state(self) -> dict: ...
    def round_end_payload(self) -> dict: ...
    def game_end_payload(self) -> dict: ...
